title: redirect to CCCL

repository: wmaxey/doc_testing

remote_theme: pmarsceill/just-the-docs

color_scheme: nvidia
logo: /assets/images/nvidia_logo.png

search_enabled: true
search.heading_level: 4

# just-the-docs ignores these filenames by default.
include: [ "contributing.md", "code_of_conduct.md" ]

plugins_dir:
  - jekyll-remote-theme
  - jekyll-optional-front-matter # GitHub Pages.
  - jekyll-default-layout        # GitHub Pages.
  - jekyll-titles-from-headings  # GitHub Pages.
  - jekyll-relative-links        # GitHub Pages.

defaults:
  -
    scope:
      path: overview.md
    values:
      title: Overview
      nav_order: 0
      permalink: /